spring:
  application:
    name: user-register
  datasource:
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    username: root
    password: zahiri


email:
  host: smtp-gmail.com
  port: 5432
